name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      
      - name: Get main branch (only want to lint the new code that is different from main)
        run: git fetch origin main
      
      - name: Lint code for consistent style
        run: git diff origin/main --name-only | xargs bin/rubocop --force-exclusion